students/urls.py
from django.conf.urls import url
from registration.backends.default.views import RegistrationView
from .forms import *

from . import views
app_name='students'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/$', views.details, name='details'),
    url(r'^allUsers/$', views.allUsers, name='allUsers'),
    url(r'^register/$', views.register, name='register'), # ADD NEW PATTERN!
]

thePOKS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from students.forms import *
from students.regbackend import MyRegistrationView

# class MyRegistrationView(RegistrationView):
#         def get_success_url(self, request, user):
#             return '/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('students.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^tests/', include('tests.urls')),
    url(r'^select2/', include('django_select2.urls')),
]

students/models.py
from django.db import models
from django.contrib.auth.models import User

class StudyGroup(models.Model):
    groupName = models.CharField(max_length=6)

    def __str__(self):
        return self.groupName


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    birthDate = models.DateField(auto_now_add=True)
    studygroup = models.ForeignKey(StudyGroup,on_delete=None,default=0)

def getFullName(self):
    return self.get_full_name()

User.add_to_class("__str__", getFullName)

students/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *
from registration.forms import RegistrationForm
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.admin.widgets import AdminDateWidget
from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
from django.utils.translation import ugettext_lazy as _


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password','email','first_name','last_name')
        widgets = {
            'password': forms.PasswordInput(),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = StudyGroup
        fields = ('groupName',)
        widgets = {
            'groupName': ModelSelect2Widget(
                            queryset=StudyGroup.objects.all(),
                            search_fields=['groupName__icontains']
                        ,attrs={'class': 'selectpicker'})
        }
        labels = {
            'groupName': _('Группа')
        }

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = StudyGroup
#         fields = ('groupName',)
#         widgets = {
#             'groupName': ModelSelect2MultipleWidget(
#                             queryset=StudyGroup.objects.all(),
#                             search_fields=['groupName__icontains']
#                         ,attrs={'class': 'selectpicker'})
#         }

students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from registration.forms import RegistrationForm
from .forms import *
from django.contrib.auth import login

import datetime

def index(request):
    return render(request,'index.html')

def details(request):
    user = User.objects.get(pk=request.user.id)
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            return HttpResponseRedirect('/')
    else:
        form = UserForm(instance=user)
    return render(request,'students/userInfo.html',{'context': request.user,'form':form})

def allUsers(request):
    all_users = User.objects.all().order_by('username')
    paginator = Paginator(all_users, 10) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        users = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        users = paginator.page(paginator.num_pages)

    return render(request, 'students/index.html', {'users': users})

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        print(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            group = StudyGroup.objects.get(pk=request.POST['groupName'])
            print(group)
            profile = UserProfile(user=user,studygroup=group)
            profile.save()
            registered = True
        else:
            user_form.errors#, profile_form.errors
        if registered:
            login(request, user)
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/')
    else:
        user_form = UserForm()
        profile = ProfileForm()
        profile = render_to_string('basePicker.html',{'form':profile},request)

    return render(request,
            'registration/registration_form.html',
            {'user_form': user_form,'form':profile} )

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load students_extras %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <title>{% block title %}User test{% endblock %}</title>
</head>

<body>
  <div id="header">
    {% block header %}
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Добро пожаловать, {{ user.get_full_name }}!<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'students:details' %}">Личная страница</a></li>
                    <li><a href="{% url 'tests:usersTests' %}">Результаты</a></li>
                    <li class="divider"></li>
                    {% if user|has_group:"teachers" %}
                      <li><a href="{% url 'tests:uploadFile' %}">Добавить тест</a></li>
                    {% endif %}
                    <li><a href="{% url 'tests:myTests' %}">Тесты</a></li>
                    <li class="divider"></li>
                    {% if user.is_staff %}
                      <li><a href="{% url 'students:allUsers' %}">Все пользователи</a></li>
                    {% endif %}
                  </ul>
                </li>
                <li><a href="{% url 'students:index' %}" class="btn btn-default">Домой</a></li>
                <li><a href="{% url 'auth_password_change' %}" class="btn btn-default">{% trans "Change password" %}</a></li>
                <li><a href="{% url 'tests:indexSub' %}" class="btn btn-default">Тесты</a></li>
              {% endif %}
            </ul>
            {% if user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
              </ul>
              {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'auth_login' %}">{% trans "Log in" %}</a></li>
              </ul>
            {% endif %}
          </div>
        </div>
      </nav>
    {% endblock %}
  </div>
    <div id="content" class="container" style="min-height:500px;">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/my-ajax.js' %}"></script>
    <script src="{% static 'js/d3.v3.min.js' %}"></script>
</body>

</html>

templates/basePicker.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  {{ form.media.css }}
  <style type="text/css">
    div.col-md-10 > label {
      margin-right: 40px;
    }
    select {
      width: 380px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <form method="post" action="">
          {% csrf_token %}
          {{ form }}
        </form>
      </div>
    </div>
  </div>
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript">
  window.onerror = function (msg) {
    $("body").attr("JSError", msg);
  }
</script>
{{ form.media.js }}
</body>

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="">
  {% if not user.is_authenticated %}
  <div class="jumbotron">
    <h1>Добро пожаловать!</h1>
    <p>Пожалуйста, авторизуйтесь.</p>
    <p><a href="{% url 'auth_login' %}" class="btn btn-primary">{% trans "Log in" %}</a></p>
  </div>
  {% else %}
  <div class="jumbotron">
    <h1>Добро пожаловать!</h1>
    <p>Приятной работы</p>
    <p><a href="{% url 'tests:indexSub' %}" class="btn btn-primary">Тесты</a></p>
  </div>
  {% endif %}
</div>
{% endblock %}

templates/picker.html
{% load staticfiles %}
{% load staticfiles %}
{% load i18n %}
{% load students_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
  {{ form.media.css }}
  <style type="text/css">
    div > label {
      margin-right: 40px;
    }
    select {
      width: 380px;
    }
  </style>
</head>
<body>
<div id="header">
    {% block header %}
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Добро пожаловать, {{ user.username }}!<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'students:details' %}">Личная страница</a></li>
                    <li><a href="{% url 'tests:usersTests' %}">Результаты</a></li>
                    {% if user|has_group:"teachers" %}
                      <li><a href="{% url 'tests:uploadFile' %}">Добавить тест</a></li>
                    {% endif %}

                    <li class="divider"></li>
                    <li><a href="{% url 'tests:myTests' %}">Тесты</a></li>
                    <li class="divider"></li>
                    {% if user.is_staff %}
                      <li><a href="{% url 'students:allUsers' %}">Все пользователи</a></li>
                    {% endif %}
                  </ul>
                </li>
                <li><a href="{% url 'students:index' %}" class="btn btn-default">Домой</a></li>
                <li><a href="{% url 'auth_password_change' %}" class="btn btn-default">{% trans "Change password" %}</a></li>
                <li><a href="{% url 'tests:indexSub' %}" class="btn btn-default">Тесты</a></li>
              {% endif %}
            </ul>
            {% if user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
              </ul>
              {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'auth_login' %}">{% trans "Log in" %}</a></li>
              </ul>
            {% endif %}
          </div>
        </div>
      </nav>
    {% endblock %}
  </div>
<div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        {% csrf_token %}
        {{ form }}
        <button data-type="{{ flag }}" class="btn btn-warning getStats" type="button">Просмотреть</button>
      </div>
    </div>
    <div id="groupRender">
    </div>
</div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/my-ajax.js' %}"></script>
    <script src="{% static 'js/d3.v3.min.js' %}"></script>

</body>
<script type="text/javascript">
  window.onerror = function (msg) {
    $("body").attr("JSError", msg);
  }
</script>
{{ form.media.js }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>

templates/students/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
  <ul class="list-group">
  {% for user in users %}
    <li class="list-group-item">
      {{user.username}}
    </li>
  {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
        {% if users.has_previous %}
            <a href="?page={{ users.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ users.number }} of {{ users.paginator.num_pages }}.
        </span>

        {% if users.has_next %}
            <a href="?page={{ users.next_page_number }}">next</a>
        {% endif %}
    </span>
  </div>

</div>
{% endblock %}

templates/students/userInfo.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="col-md-6">
      <form id="form" method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {% csrf_token %}
        {{ form|crispy }}
      </form>
      <input onclick="$('#myPleaseWait').modal('show');" type="submit" class="btn btn-default" name="submit" value="TEST" />
    </div>
  </form>
  <!-- Modal Start here-->
  <div class="modal fade bs-example-modal-sm" id="myPleaseWait" tabindex="-1"
      role="dialog" aria-hidden="true" data-backdrop="static">
      <div class="modal-dialog modal-sm">
          <div class="modal-content">
              <div class="modal-header">
                  <h4 class="modal-title">
                      <span class="glyphicon glyphicon-time">
                      </span>  Пожалуйста, подождите
                   </h4>
              </div>
              <div class="modal-body">
                  <div class="progress">
                      <div class="progress-bar progress-bar-info
                      progress-bar-striped active"
                      style="width: 100%">
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Modal ends Here -->
</div>
{% endblock %}